// Fictional, SpaceX-themed investment products for the demo. Not financial advice,
// not affiliated with SpaceX — this is a design/prototype exercise.

export const OPPORTUNITIES = [
  {
    id: 'starship',
    name: 'Starship Program',
    ticker: 'STRSHP',
    category: 'Flagship Vehicle',
    tag: 'Most popular',
    risk: 'High',
    price: 480,
    projected: 34.5,
    fundedPct: 78,
    raiseM: 1200,
    horizon: '5–7 yr',
    blurb:
      'The fully reusable super-heavy launch system built to carry crew and cargo to Earth orbit, the Moon, and Mars.',
    highlights: [
      '150 t payload to LEO, fully reusable',
      'Backlog of lunar & commercial flights',
      'Rapid-reflight economics',
    ],
    accent: 'flare',
  },
  {
    id: 'starlink',
    name: 'Starlink Broadband',
    ticker: 'STRLNK',
    category: 'Recurring Revenue',
    tag: 'Cash-flow',
    risk: 'Medium',
    price: 210,
    projected: 22.1,
    fundedPct: 64,
    raiseM: 2500,
    horizon: '3–5 yr',
    blurb:
      'A low-Earth-orbit constellation delivering high-speed internet to millions of subscribers worldwide.',
    highlights: [
      '6,000+ satellites operational',
      '5M+ subscribers across 100+ countries',
      'Predictable subscription revenue',
    ],
    accent: 'flare',
  },
  {
    id: 'falcon9',
    name: 'Falcon 9 Launch Cadence',
    ticker: 'FLCN9',
    category: 'Launch Services',
    tag: 'Stable',
    risk: 'Low',
    price: 145,
    projected: 12.8,
    fundedPct: 91,
    raiseM: 600,
    horizon: '2–3 yr',
    blurb:
      'The workhorse reusable rocket with the highest launch cadence in history and a deep commercial manifest.',
    highlights: [
      '300+ successful missions',
      'Booster reuse under 30 days',
      'Diversified customer base',
    ],
    accent: 'flare',
  },
  {
    id: 'dragon',
    name: 'Dragon Crew & Cargo',
    ticker: 'DRGN',
    category: 'Human Spaceflight',
    tag: 'NASA-backed',
    risk: 'Low',
    price: 165,
    projected: 14.6,
    fundedPct: 83,
    raiseM: 450,
    horizon: '2–4 yr',
    blurb:
      'The only U.S. spacecraft flying astronauts to the ISS, plus private crewed missions and cargo resupply.',
    highlights: [
      'Multiple NASA contracts',
      'Autonomous docking & reentry',
      'Private astronaut demand rising',
    ],
    accent: 'flare',
  },
  {
    id: 'raptor',
    name: 'Raptor Engine Works',
    ticker: 'RPTR',
    category: 'Propulsion',
    tag: 'Manufacturing',
    risk: 'Medium',
    price: 120,
    projected: 19.3,
    fundedPct: 57,
    raiseM: 800,
    horizon: '3–5 yr',
    blurb:
      'Full-flow staged-combustion methalox engines produced at scale — the heart of Starship and Super Heavy.',
    highlights: [
      'Highest thrust-to-weight class',
      'Designed for Mars-made propellant',
      'Vertically integrated production',
    ],
    accent: 'plasma',
  },
  {
    id: 'starshield',
    name: 'Starshield Defense',
    ticker: 'SHLD',
    category: 'Government / Defense',
    tag: 'Contracted',
    risk: 'Medium',
    price: 260,
    projected: 24.9,
    fundedPct: 41,
    raiseM: 1500,
    horizon: '4–6 yr',
    blurb:
      'Secure, hardened satellite services for national-security customers built on the Starlink platform.',
    highlights: [
      'Encrypted government payloads',
      'Long-duration contract pipeline',
      'Resilient mesh architecture',
    ],
    accent: 'plasma',
  },
  {
    id: 'mars',
    name: 'Mars Colonization Fund',
    ticker: 'MARS',
    category: 'Frontier / Venture',
    tag: 'Moonshot',
    risk: 'Very High',
    price: 999,
    projected: 62.0,
    fundedPct: 29,
    raiseM: 5000,
    horizon: '10+ yr',
    blurb:
      'A long-horizon fund backing the propellant depots, habitats, and surface systems for a self-sustaining Mars city.',
    highlights: [
      'Frontier upside, frontier risk',
      'In-situ resource utilisation R&D',
      'The multi-planetary thesis',
    ],
    accent: 'plasma',
  },
  {
    id: 'lunar',
    name: 'Lunar Gateway Logistics',
    ticker: 'LUNAR',
    category: 'Cislunar',
    tag: 'Artemis',
    risk: 'High',
    price: 340,
    projected: 28.4,
    fundedPct: 48,
    raiseM: 1100,
    horizon: '5–8 yr',
    blurb:
      'Cargo and crew logistics supporting a sustained human presence in cislunar space and on the lunar surface.',
    highlights: [
      'Human Landing System heritage',
      'Recurring resupply demand',
      'Deep-space refueling upside',
    ],
    accent: 'plasma',
  },
];

export function getOpportunity(id) {
  return OPPORTUNITIES.find((o) => o.id === id) || null;
}

export const RISK_ORDER = { Low: 0, Medium: 1, High: 2, 'Very High': 3 };
